cpp module naming rfc
ArkScript-lang/rfc pull request #3
Opened 2020-10-08 13:53 UTC by PierrePharel

2020-10-08 19:58 UTC, SuperFola requested changes

2020-10-08 19:58 UTC, SuperFola commented on 003-naming-convention.md
> +It must follow SnakeCase naming convention like : `name_operation_...` where `name` is the name of module, `operation` what the function do and `...` mean the rest of name of function, but the recomm
It's usually written snake_case (while we write PascalCase and camelCase)

Also, "what the function do**es**"

2020-10-09 09:17 UTC, PierrePharel commented on 003-naming-convention.md
> +It must follow SnakeCase naming convention like : `name_operation_...` where `name` is the name of module, `operation` what the function do and `...` mean the rest of name of function, but the recomm
ok

2020-10-09 11:51 UTC, SuperFola commented on 003-naming-convention.md
> +It must follow **snake_case** naming convention like : `name_operation_...` where `name` is the name of module, `operation` what the function does and `...` mean the rest of name of function, but the
sorry i must missed it, it's "mean**s**" not "mean" (=> *means the rest of the function's name*)

appart from spelling and grammar, that's fine to me

2020-10-09 17:56 UTC, SuperFola approved these changes

2020-10-09 17:56 UTC, merged